In [94]:
%load_ext autoreload
%autoreload 2
%cd ~/austin_big_vision
import io
import os
import jax
import json
import torch
import importlib
import numpy as np
import ml_collections
import jax.numpy as jnp
import tensorflow as tf

import open_clip
import big_vision.utils as u
import big_vision.models.vit as model_mod
from big_vision.models.vit import scan_to_pyloop

from datasets import load_dataset

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/austinwang/austin_big_vision


/mnt/vlm-pd/miniconda3/envs/vlm/lib/python3.10/site-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
/mnt/vlm-pd/miniconda3/envs/vlm/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [95]:
examples = load_dataset('facebook/winoground', use_auth_token="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",trust_remote_code=True)['test']

/mnt/vlm-pd/miniconda3/envs/vlm/lib/python3.10/site-packages/datasets/load.py:2566: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(


In [96]:
# Hyperparameters
backbone = 'gemma2b-half-0.1_b16-F_contrastive'

# setup
backbone_dict = {
    'clip': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_bs16384_warm10k_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_07-23_1510',
    'clip_map': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_autoregressive_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_06-24_2019',
    'clip_s9b': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_autoregressive_s9b_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_08-04_0839',
    'clip_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_s9b_bs32k_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_08-09_0655',
    'siglip': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_parallel_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_06-24_2019',
    'siglip_v4-32': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_replication_pod_04-11_2247',
    'siglip_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_s9b_bs32k_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_08-04_0839',
    'cappa': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/cappa_bs16384_s3B_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-27_2108',
    # 'cappa_decoder-qknorm-T_warm0.02': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs16384_warm0.02_lr1e-3_wd1e-4_bf16_b2-0.95_6lyr_06-15_2102',
    'cappa_s9b': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs16384_s9B_warm0.02_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-27_2108',
    'cappa_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs32768_s9B_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_08-07_2217',
    'coca_6lyr': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_bs16384_warm0.03_1.0co-2.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-30_1841',
    'coca_unified': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_s3b_bs16384_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-19_0355',
    'coca_1.0co_1.0ca_6lyr_qknorm-T_warm0.02': 'gs://us-central2-storage/tensorflow_datasets/ckpts/coca_replication_bs16384_warm0.02_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_b2-0.95_6lyr_06-10_2225',
    'coca': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_bs32768_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-12_2313',
    'coca_6lyr_1.0co_1.0ca_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_s9b_bs32768_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-14_1614',
    'gemma2b-half-0.1_b16-F_contrastive': 'gs://us-central2-storage/tensorflow_datasets/mllm_ckpts/paligemma/gemma2b-half-0.1_so400m-F_contrastive_bs16384_s3b_wd1e-4_08-21_1935',
}
backbone_path = backbone_dict[backbone]
config_path = f'{backbone_path}/config.json'
config = ml_collections.ConfigDict(json.load(tf.io.gfile.GFile(config_path, "r")))
ckpt_path = f'{backbone_path}/checkpoint.bv-{config.total_steps:09d}'

# load model
model_cfg = config.model
img_key = 'img' if 'image' in model_cfg or 'img' in model_cfg else 'encoder'
model_mod = importlib.import_module(f"big_vision.models.{config.model_name}")
bv_model = model_mod.Model(**model_cfg)

In [97]:
# load ckpt weights
rng = jax.random.PRNGKey(42)
dummy_img = jnp.zeros([2, 224, 224, 3], jnp.float32)
dummy_txt = jnp.zeros([2, 64], jnp.int32)
dummy_mask_ar = jnp.zeros([2, 64], jnp.bool_) if 'llm' in model_cfg else None
if dummy_mask_ar is not None:
    init_params = jax.jit(bv_model.init, backend="cpu")(rng, dummy_img, dummy_txt,dummy_mask_ar)['params']
else:
    init_params = jax.jit(bv_model.init, backend="cpu")(rng, dummy_img, dummy_txt)['params']

img_load_kw = {'dont_load': ('.*_ln/scale','head/kernel', 'head/bias')}
params = model_mod.load(init_params, ckpt_path, model_cfg, img_load_kw)
jax.tree_map(jnp.shape, params)

/tmp/ipykernel_154633/4280382188.py:13: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  jax.tree_map(jnp.shape, params)


{'img': {'Transformer': {'encoder_norm': {'bias': (768,), 'scale': (768,)},
   'encoderblock': {'LayerNorm_0': {'bias': (12, 768), 'scale': (12, 768)},
    'LayerNorm_1': {'bias': (12, 768), 'scale': (12, 768)},
    'MlpBlock_0': {'Dense_0': {'bias': (12, 3072), 'kernel': (12, 768, 3072)},
     'Dense_1': {'bias': (12, 768), 'kernel': (12, 3072, 768)}},
    'MultiHeadDotProductAttention_0': {'key': {'bias': (12, 12, 64),
      'kernel': (12, 768, 12, 64)},
     'out': {'bias': (12, 768), 'kernel': (12, 12, 64, 768)},
     'query': {'bias': (12, 12, 64), 'kernel': (12, 768, 12, 64)},
     'value': {'bias': (12, 12, 64), 'kernel': (12, 768, 12, 64)}}}},
  'embedding': {'bias': (768,), 'kernel': (16, 16, 3, 768)},
  'head': {'bias': (2048,), 'kernel': (768, 2048)},
  'pos_embedding': (1, 196, 768)},
 'llm': {'embedder': {'input_embedding': (257152, 2048)},
  'final_norm': {'scale': (2048,)},
  'layers': {'attn': {'attn_vec_einsum': {'w': (9, 8, 256, 2048)},
    'kv_einsum': {'w': (9, 2, 1

In [98]:
import importlib
import big_vision.pp.builder as pp_builder
for m in config.get("pp_modules", ["ops_general", "ops_image", "ops_text"]): importlib.import_module(f"big_vision.pp.{m}")

pp_img_idx = config.input.pp.split('|').index('value_range(-1,1)')
pp_img = pp_builder.get_preprocess_fn('|'.join(config.input.pp.split('|')[1:pp_img_idx+1]))
pp_txt = pp_builder.get_preprocess_fn('|'.join(config.input.pp.split('|')[pp_img_idx+1:]))
pp = pp_builder.get_preprocess_fn(config.input.pp)

In [99]:
example = examples[0]
image_0 = pp_img({"image": jnp.asarray(example['image_0'])})['image'][None,:]
image_1 = pp_img({"image": jnp.asarray(example['image_1'])})['image'][None,:]
caption_0 = pp_txt({"caption": example['caption_0']})
caption_1 = pp_txt({"caption": example['caption_1']})

In [100]:
caption_0

{'text': <tf.Tensor: shape=(65,), dtype=int32, numpy=
 array([    2,   108,   481,  2187,  1552, 68129,   476,  3486,  1552,
            1,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0], dtype=int32)>,
 'mask_ar': <tf.Tensor: shape=(65,), dtype=int32, numpy=
 array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int32)>,
 'mask_loss': <tf.Tensor: shape=(65,), dtype=int32, numpy=
 array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 

In [101]:
zimg_0, out_img_0 = bv_model.apply({"params":params}, image_0, method='embed_image')
zimg_1, out_img_1 = bv_model.apply({"params":params}, image_1, method='embed_image')

In [102]:
ztxt_0 = bv_model.apply({"params":params}, None, caption_0['text'][:,:-1], caption_0['mask_ar'][:,:-1], is_blind=True)[1]['llm/head_input']

2024-08-28 21:04:16.888241: W tensorflow/core/framework/op_kernel.cc:1840] OP_REQUIRES failed at strided_slice_op.cc:117 : INVALID_ARGUMENT: Index out of range using input dim 1; input has only 1 dims


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} Index out of range using input dim 1; input has only 1 dims [Op:StridedSlice] name: strided_slice/

In [ ]:
zimg_0.shape

(1, 196, 2048)

In [ ]:
def cosine_similarity(a, b):
    if a.ndim == 2: 
        a = a[None]
        b = b[None]
    def sim(a_i, b_i):
        return np.dot(a_i, b_i) / (np.linalg.norm(a_i) * np.linalg.norm(b_i))
    sim_list = [sim(a_i, b_i) for a_i, b_i in zip(a[0], b[0])]
    return np.mean(sim_list)

cosine_similarity(zimg_0, zimg_1)

0.24476762