In [84]:
%load_ext autoreload
%autoreload 2
%cd ~/austin_big_vision
import jax
import json
import torch
import importlib
import numpy as np
import ml_collections
import jax.numpy as jnp
import tensorflow as tf
from datasets import load_dataset

import big_vision.utils as u
import big_vision.pp.builder as pp_builder

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/austinwang/austin_big_vision


/mnt/vlm-pd/miniconda3/envs/vlm/lib/python3.10/site-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
/mnt/vlm-pd/miniconda3/envs/vlm/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [85]:
examples = load_dataset('facebook/winoground', token="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",trust_remote_code=True)['test']

def compute_winoground_scores(i0_c0,i0_c1,i1_c0,i1_c1):
    print("Computing Winoground scores")
    # text scores: 1 if i0_c0 > i0_c1 and i1_c1 > i1_c0, 0 otherwise
    # image scores: 1 if i0_c0 > i1_c0 and i1_c1 > i0_c1, 0 otherwise
    text_scores = (i0_c0 > i0_c1) & (i1_c1 > i1_c0)
    image_scores = (i0_c0 > i1_c0) & (i1_c1 > i0_c1)
    both_scores = text_scores & image_scores
    def get_acc(scores): 
        # return eg.72.50%
        s = scores.mean().item()*100
        return f'{s:.2f}'
    print("Text Score:", get_acc(text_scores))
    print("Image Score:", get_acc(image_scores))
    print("Both Score:", get_acc(both_scores))

# Big_Vision

In [86]:
# Hyperparameters
backbone = 'gemma2b-half-0.1_b16-F_contrastive'
backbone = 'clip_s9b_bs32k'

# setup
backbone_dict = {
    'clip': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_bs16384_warm10k_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_07-23_1510',
    'clip_replication': 'gs://us-central2-storage/tensorflow_datasets/clip-replication_autoregressive_bs32768_warm0.03_lr5e-4_wd1e-4_bf16_qknorm-F_b1-0.9_b2-0.98_12lyr_06-24_2019',
    'clip_map': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_autoregressive_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_06-24_2019',
    'clip_s9b': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_autoregressive_s9b_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_08-04_0839',
    'clip_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_s9b_bs32k_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_08-09_0655',
    'siglip': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_parallel_bs16384_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_12lyr_06-24_2019',
    'siglip_v4-32': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_replication_pod_04-11_2247',
    'siglip_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/siglip_s9b_bs32k_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_08-04_0839',
    'cappa': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/cappa_bs16384_s3B_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-27_2108',
    # 'cappa_decoder-qknorm-T_warm0.02': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs16384_warm0.02_lr1e-3_wd1e-4_bf16_b2-0.95_6lyr_06-15_2102',
    'cappa_s9b': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs16384_s9B_warm0.02_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-27_2108',
    'cappa_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/cappa_bs32768_s9B_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_08-07_2217',
    'coca_6lyr': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_bs16384_warm0.03_1.0co-2.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_06-30_1841',
    'coca_unified': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_s3b_bs16384_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-19_0355',
    'coca_1.0co_1.0ca_6lyr_qknorm-T_warm0.02': 'gs://us-central2-storage/tensorflow_datasets/ckpts/coca_replication_bs16384_warm0.02_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_b2-0.95_6lyr_06-10_2225',
    'coca': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_bs32768_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-12_2313',
    'coca_6lyr_1.0co_1.0ca_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_replication_s9b_bs32768_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-14_1614',
    'coca_unified_s9b_bs32k': 'gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/coca_unified_s9b_bs32768_warm0.03_1.0co-1.0ca_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_6lyr_scan-F_fsdp-F_08-20_0246',
    'gemma2b-half-0.1_b16-F_contrastive': 'gs://us-central2-storage/tensorflow_datasets/mllm_ckpts/paligemma/gemma2b-half-0.1_so400m-F_contrastive_bs16384_s3b_wd1e-4_08-21_1935',
}
backbone_path = backbone_dict[backbone]
config_path = f'{backbone_path}/config.json'
config = ml_collections.ConfigDict(json.load(tf.io.gfile.GFile(config_path, "r")))
for m in config.get("pp_modules", ["ops_general", "ops_image", "ops_text"]): importlib.import_module(f"big_vision.pp.{m}")

# load model
print(f"Loading model")
model_cfg = config.model
if 'proj_bias' not in model_cfg.text and backbone.split('_')[0]=="siglip": model_cfg.text.proj_bias = True
img_key = 'img' if 'image' in model_cfg or 'img' in model_cfg else 'encoder'
model_mod = importlib.import_module(f"big_vision.models.{config.model_name}")
bv_model = model_mod.Model(**model_cfg)

# load ckpt weights
print(f'Loading weights from {backbone_path}')
rng = jax.random.PRNGKey(42)
dummy_img = jnp.zeros([2, 224, 224, 3], jnp.float32)
dummy_txt = jnp.zeros([2, 64], jnp.int32)
dummy_mask_ar = jnp.zeros([2, 64], jnp.bool_) if 'llm' in model_cfg else None
if dummy_mask_ar is not None:
    init_params = jax.jit(bv_model.init, backend="cpu")(rng, dummy_img, dummy_txt,dummy_mask_ar)['params']
else:
    init_params = jax.jit(bv_model.init, backend="cpu")(rng, dummy_img, dummy_txt)['params']

# img_load_kw = {'dont_load': ('.*_ln/scale','head/kernel', 'head/bias')}
ckpt_path = f'{backbone_path}/checkpoint.bv-{config.total_steps:09d}'
params = model_mod.load(init_params, ckpt_path, model_cfg) # , img_load_kw)
jax.tree_map(jnp.shape, params)

Loading model
Loading weights from gs://us-central2-storage/tensorflow_datasets/vit-b-16_3b_pretraining/clip_s9b_bs32k_warm0.03_lr1e-3_wd1e-4_bf16_qknorm-F_b2-0.95_08-09_0655


/tmp/ipykernel_412090/1932418312.py:54: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  jax.tree_map(jnp.shape, params)


{'img': {'Transformer': {'encoder_norm': {'bias': (768,), 'scale': (768,)},
   'encoderblock': {'LayerNorm_0': {'bias': (12, 768), 'scale': (12, 768)},
    'LayerNorm_1': {'bias': (12, 768), 'scale': (12, 768)},
    'MlpBlock_0': {'Dense_0': {'bias': (12, 3072), 'kernel': (12, 768, 3072)},
     'Dense_1': {'bias': (12, 768), 'kernel': (12, 3072, 768)}},
    'MultiHeadDotProductAttention_0': {'key': {'bias': (12, 12, 64),
      'kernel': (12, 768, 12, 64)},
     'out': {'bias': (12, 768), 'kernel': (12, 12, 64, 768)},
     'query': {'bias': (12, 12, 64), 'kernel': (12, 768, 12, 64)},
     'value': {'bias': (12, 12, 64), 'kernel': (12, 768, 12, 64)}}}},
  'embedding': {'bias': (768,), 'kernel': (16, 16, 3, 768)},
  'head': {'kernel': (768, 768)},
  'pos_embedding': (1, 196, 768)},
 't': (1,),
 'txt': {'Embed_0': {'embedding': (32000, 768)},
  'Encoder_0': {'encoder_norm': {'bias': (768,), 'scale': (768,)},
   'encoderblock': {'LayerNorm_0': {'bias': (12, 768), 'scale': (12, 768)},
    'L

In [87]:
print(f"Applying preprocessing: {config.input.pp}")
pp_img_idx = config.input.pp.split('|').index('value_range(-1,1)')
pp_list = config.input.pp.split('|')
assert pp_list[0] == 'decode'
pp_img = pp_builder.get_preprocess_fn('|'.join(pp_list[1:pp_img_idx+1]))
pp_txt = pp_builder.get_preprocess_fn('|'.join(pp_list[pp_img_idx+1:]))
print("Preprocessing images")
i0 = jnp.array([pp_img({"image": jnp.asarray(img.convert('RGB'))})['image'] for img in examples['image_0']])
i1 = jnp.array([pp_img({"image": jnp.asarray(img.convert('RGB'))})['image'] for img in examples['image_1']])
print("Preprocessing text")
c0_list, c0 = [pp_txt({"caption": txt}) for txt in examples['caption_0']], {}
for k in c0_list[0].keys(): c0[k] = jnp.array([d[k] for d in c0_list])
c1_list, c1 = [pp_txt({"caption": txt}) for txt in examples['caption_1']], {}
for k in c1_list[0].keys(): c1[k] = jnp.array([d[k] for d in c1_list])
print(f"i0.shape: {i0.shape}, c0 shapes: {jax.tree.map(lambda x: x.shape, c0)}")

Applying preprocessing: decode|resize(224)|flip_lr|value_range(-1,1)|tokenize(max_len=64, model="c4_en", clip_bpe=False, eos="sticky", pad_value=1, inkey="caption", outkey="labels")|keep("image", "labels")
Preprocessing images


In [ ]:
def mean_normalize(x): 
    if len(x.shape) == 3: x = x.mean(1)
    return x / jnp.linalg.norm(x, axis=-1, keepdims=True)

def encode_img(img,model_type=backbone.split('_')[0]):
    if model_type == 'clip' or model_type == 'siglip':
        zimg, _, _ = bv_model.apply({"params":params}, img)
    elif model_type == 'cappa' or model_type == 'coca':
        encoded, _ = bv_model.apply({"params":params}, img, return_enc_features=True, method = 'encode')
        return encoded
    elif model_type.split('-')[0] == 'gemma2b':
        encoded, _ = bv_model.apply({"params":params}, img, method='embed_image')
        zimg = mean_normalize(encoded)
    return zimg

def encode_txt(txt,model_type=backbone.split('_')[0]):
    if model_type == 'clip' or model_type == 'siglip':
        _, ztxt, _ = bv_model.apply({"params":params}, None, text=txt['labels'])
    elif model_type.split('-')[0] == 'gemma2b':
        assert isinstance(txt, dict), f"txt must be a dict, got {type(txt)}"
        ztxt, _ = bv_model.apply({"params":params}, None, txt['text'][:,:-1], txt['mask_ar'][:,:-1],is_blind=True)[1]['llm/pre_logits']
        ztxt = mean_normalize(ztxt)
    return ztxt

def bv_perplexity(img,txt):
    print("Encoding image")
    encoded = encode_img(img)
    print("Decoding image to text")
    out = bv_model.apply({"params": params}, encoded, txt['labels'], method='decode')
    if isinstance(out, tuple):
        print("Computing similarity")
        logits, ztxt = out
        zimg = mean_normalize(encoded)
        ztxt = mean_normalize(ztxt)
        sim = jnp.sum(zimg * ztxt, axis=-1)
    else:
        logits = out
        sim = None
    weights = jnp.where(txt['labels'] != 0, 1, 0).astype(jnp.float32)
    print("Computing perplexities")
    losses = u.weighted_softmax_xent(
        logits=logits, labels=txt['labels'],
        weights=weights, label_smoothing=0.0,
        reduction=False, normalize=False)
    return {
        "perplexity": losses * -1,
        "similarity": sim,
    }

In [ ]:
model_type = backbone.split('_')[0]
print(f"Computing logits for {model_type} model")
if model_type in ['clip','siglip']:
    print("Computing image embeddings")
    zi0, zi1 = encode_img(i0), encode_img(i1)
    print("Computing text embeddings")
    zc0, zc1 = encode_txt(c0), encode_txt(c1)
    print("Computing similarities")
    i0_c0 = jnp.sum(zi0 * zc0, axis=-1)
    i0_c1 = jnp.sum(zi0 * zc1, axis=-1)
    i1_c0 = jnp.sum(zi1 * zc0, axis=-1)
    i1_c1 = jnp.sum(zi1 * zc1, axis=-1)

elif model_type in ['cappa','coca']:
    i0_c0 = bv_perplexity(i0,c0)
    i0_c1 = bv_perplexity(i0,c1)
    i1_c0 = bv_perplexity(i1,c0)
    i1_c1 = bv_perplexity(i1,c1)



Computing logits for clip model
Computing image embeddings
Computing text embeddings
Computing similarities


In [ ]:
if isinstance(i0_c0,dict):
    for k in i0_c0.keys():
        print(f"Computing scores from {k}")
        compute_winoground_scores(i0_c0[k],i0_c1[k],i1_c0[k],i1_c1[k])
else:
    compute_winoground_scores(i0_c0,i0_c1,i1_c0,i1_c1)

Computing Winoground scores
Text Score: 30.00
Image Score: 11.00
Both Score: 7.50


# Open_CLIP

In [56]:
import open_clip
# open_clip_ckpt = "/home/austinwang/vit_b_16-laion400m_e32-55e67d44.pt"
open_clip_model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-16', pretrained="datacomp_xl_s13b_b90k")
tokenizer = open_clip.get_tokenizer('ViT-B-16')

In [57]:
i0 = torch.cat([preprocess(examples[i]['image_0'].convert('RGB')).unsqueeze(0) for i in range(len(examples))])
i1 = torch.cat([preprocess(examples[i]['image_1'].convert('RGB')).unsqueeze(0) for i in range(len(examples))])
c0 = tokenizer(examples['caption_0'])
c1 = tokenizer(examples['caption_1'])

In [58]:
with torch.no_grad():
    print("Encoding images")
    zi0 = open_clip_model.encode_image(i0)
    zi1 = open_clip_model.encode_image(i1)
    print("Encoding text")
    zc0 = open_clip_model.encode_text(c0)
    zc1 = open_clip_model.encode_text(c1)

Encoding images
Encoding text


In [59]:
i0_c0 = (zi0 * zc0).sum(-1).cpu().numpy()
i0_c1 = (zi0 * zc1).sum(-1).cpu().numpy()
i1_c0 = (zi1 * zc0).sum(-1).cpu().numpy()
i1_c1 = (zi1 * zc1).sum(-1).cpu().numpy()

In [60]:
i0_c0[:5],i0_c1[:5],i1_c0[:5],i1_c1[:5]

(array([65.69056 , 39.836163, 57.971386, 28.234322, 44.676838],
       dtype=float32),
 array([65.88536 , 37.76516 , 60.367546, 30.57318 , 43.058273],
       dtype=float32),
 array([72.750755, 53.282722, 62.647163, 45.93105 , 39.767345],
       dtype=float32),
 array([71.42322 , 51.538418, 64.43231 , 53.727386, 37.324226],
       dtype=float32))

In [61]:
compute_winoground_scores(i0_c0,i0_c1,i1_c0,i1_c1)

Computing Winoground scores
Text Score: 29.25
Image Score: 7.75
Both Score: 6.50
