In [1]:
import json

cambrian_737k_path = "/mnt/disks/storage/data/finetune_data/jsons/737k.jsonl"
cambrian_10M_path = "/mnt/disks/storage/data/finetune_data/clean_9784k.json"

data = []
# with open(cambrian_737k_path, 'r') as f:
    # for line in f: data.append(json.loads(line))
with open(cambrian_10M_path, 'r') as f:
    data = json.load(f)
len(data),data[0]

(9784416,
 {'id': '000000033471',
  'image': 'coco/train2017/000000033471.jpg',
  'conversations': [{'from': 'human',
    'value': '<image>\nWhat are the colors of the bus in the image?'},
   {'from': 'gpt', 'value': 'The bus in the image is white and red.'},
   {'from': 'human',
    'value': 'What feature can be seen on the back of the bus?'},
   {'from': 'gpt', 'value': 'The back of the bus features an advertisement.'},
   {'from': 'human',
    'value': 'Is the bus driving down the street or pulled off to the side?'},
   {'from': 'gpt',
    'value': 'The bus is driving down the street, which is crowded with people and other vehicles.'}],
  'source': 'sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json'})

# turns

In [31]:
num_turns = []
cur_max = {
    'idx': -1,
    'num_turns': -1
}
for idx in range(len(data)):
    num_turns.append(len(data[idx]['conversations']))
    if len(data[idx]['conversations']) > cur_max['num_turns']:
        cur_max['idx'] = idx
        cur_max['num_turns'] = len(data[idx]['conversations'])
print(f"Max num_turns: {max(num_turns)}")
print(f"Min num_turns: {min(num_turns)}")
print(f"Avg num_turns: {sum(num_turns)/len(num_turns)}")
print(f"Max idx: {cur_max['idx'], cur_max['num_turns']}")

Max num_turns: 550
Min num_turns: 1
Avg num_turns: 3.056301367398933
Max idx: (170234, 550)


In [30]:
data[170234]

{'id': '000000150435',
 'image': 'coco/train2017/000000150435.jpg',
 'conversations': [{'from': 'human',
   'value': '<image>\nIs this person alone?\nAnswer the question using a single word or phrase.'},
  {'from': 'gpt', 'value': 'No'},
  {'from': 'human', 'value': 'Is the man smiling?'},
  {'from': 'gpt', 'value': 'Yes'},
  {'from': 'human', 'value': 'Is this man writing?'},
  {'from': 'gpt', 'value': 'No'},
  {'from': 'human', 'value': 'Who seems more happier?'},
  {'from': 'gpt', 'value': 'Men'},
  {'from': 'human',
   'value': 'How many people in this photo appear to be holding gaming controllers?'},
  {'from': 'gpt', 'value': '2'},
  {'from': 'human', 'value': "What is on the man's wrist?"},
  {'from': 'gpt', 'value': 'Watch'},
  {'from': 'human', 'value': 'What is in the guys hand?'},
  {'from': 'gpt', 'value': 'Wii remote'},
  {'from': 'human', 'value': 'Are they inside?'},
  {'from': 'gpt', 'value': 'Yes'},
  {'from': 'human', 'value': 'What color is his hair?'},
  {'from': 'g

# assertions

In [7]:
sample = data[123]
# for idx, turn in enumerate(sample['conversations']):
#     sep_exists = '\n' in turn['value']
#     is_model_response = turn['from'] == 'gpt'
#     not_valid = is_model_response and sep_exists
#     print(f"{idx}: {turn['from']} - {sep_exists} - {not_valid}")
sample

{'id': '000000536390',
 'image': 'coco/train2017/000000536390.jpg',
 'conversations': [{'from': 'human',
   'value': 'What animal is the woman riding in the image?\n<image>'},
  {'from': 'gpt', 'value': 'The woman is riding an elephant in the image.'},
  {'from': 'human',
   'value': 'Is the elephant fully or partially submerged in the water?'},
  {'from': 'gpt',
   'value': 'The elephant is partially submerged in the water. The upper part of its body and head are visible above the waterline.'},
  {'from': 'human',
   'value': 'What kind of body of water is the elephant and the woman in?'},
  {'from': 'gpt',
   'value': 'The elephant and the woman are in a river, with the elephant walking through the water and carrying the woman on its back.'},
  {'from': 'human',
   'value': 'What might be the purpose of the woman riding the elephant in the river?'},
  {'from': 'gpt',
   'value': 'The image of the woman riding an elephant in the river could depict a variety of scenarios. It could be a

In [6]:
count = 10
for idx in range(len(data)):
    if idx % 1e6 == 0: print(f"Checking idx: {idx}")
    conv = data[idx]['conversations']
    # assert conv is a list of dicts

    try:
        assert isinstance(conv, list), f"isinstance(conv, list) --> idx: {idx}, conv: {conv}"
        for i,c in enumerate(conv):
            assert isinstance(c, dict), f"isinstance(c, dict) --> idx: {idx}, conv: {conv}"
            # assert c is a dict with keys 'from' and 'value'
            assert 'from' in c, f"'from' in c --> idx: {idx}, conv: {conv}"
            assert 'value' in c, f"'value' in c --> idx: {idx}, conv: {conv}"
            # assert 'from' value is one of 'human' and 'gpt'
            assert c['from'] in ['human', 'gpt'], f"c['from'] in ['human', 'gpt'] --> idx: {idx}, conv: {conv}"
            # assert 'value' is a string
            assert isinstance(c['value'], str), f"isinstance(c['value'], str) --> idx: {idx}, conv: {conv}"
            # assert c only has 'from' and 'value' keys
            assert len(c) == 2, f"len(c) == 2 --> idx: {idx}, conv: {conv}"

            if i % 2 == 0:
                # assert 'from' is 'human' for even index
                assert c['from'] == 'human', f"c['from'] == 'human' --> idx: {idx}, conv: {conv}"
            else:
                # assert 'from' is 'gpt' for odd index
                assert c['from'] == 'gpt', f"c['from'] == 'gpt' --> idx: {idx}, conv: {conv}"

            sep_exists = '\n' in turn['value']
            is_model_response = turn['from'] == 'gpt'
            invalid = is_model_response and sep_exists
            assert not invalid, f"not invalid --> idx: {idx}, conv: {conv}"
            # assert sep only exists after 'image'
            


        assert len(conv) % 2 == 0, f"len(conv) % 2 == 0 --> idx: {idx}, conv: {conv}"
    except AssertionError as e:
        print(e)
        print(data[idx])
        count -= 1
        if count == 0: break

Checking idx: 0
len(c) == 2 --> idx: 650722, conv: [{'from': 'human', 'value': 'sentry self hosted api 504'}, {'from': 'gpt', 'text': 'A 504 error when using the Sentry self-hosted API typically indicates that the API request timed out. This means that the server hosting the API did not receive a response from the client within the expected time frame.\n\nHere are a few possible reasons for a 504 error when using the Sentry self-hosted API:\n\nSlow network connection: The API request may be taking longer than expected due to a slow network connection. Check your network connection and try again.\n\nServer overload: The server hosting the API may be overloaded with requests. Try again later when the server load has decreased.\n\nLarge dataset: If you are trying to retrieve a large amount of data, the API request may take longer than expected. Try breaking up the request into smaller chunks or optimizing the query to retrieve only the necessary data.\n\nAPI endpoint issues: There may be 

In [27]:
data[29830]

{'id': '000000057864',
 'image': 'coco/train2017/000000057864.jpg',
 'conversations': [{'from': 'human',
   'value': '<image>\nWhat is the main activity happening in the image?'},
  {'from': 'gpt',
   'value': 'The main activity happening in the image is soccer being played on a green field.'},
  {'from': 'human',
   'value': 'Is there a single person or multiple people visible in the image?'},
  {'from': 'gpt',
   'value': 'There are multiple people visible in the image, including a man with a red jersey bent holding a soccer ball and boys playing soccer on the field.'},
  {'from': 'human',
   'value': 'What is the color of the jersey worn by the man holding the soccer ball?'},
  {'from': 'gpt',
   'value': 'The man holding the soccer ball is wearing a red jersey.'},
  {'from': 'human', 'value': 'Where is the soccer game taking place?'},
  {'from': 'gpt',
   'value': 'The soccer game is taking place on a green school field.'},
  {'from': 'human',
   'value': 'What is the possible reas

# PT data

In [33]:
sbu_558 = "/mnt/disks/storage/data/pretrain_data/sbu558k/blip_laion_cc_sbu_558k.json" # 558128
sharegpt4v = [
    "/mnt/disks/storage/data/pretrain_data/ShareGPT4V/share-captioner_coco_lcs_sam_1246k_1107.json",
    "/mnt/disks/storage/data/pretrain_data/ShareGPT4V/sharegpt4v_instruct_gpt4-vision_cap100k.json",
    "/mnt/disks/storage/data/pretrain_data/ShareGPT4V/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json",
]
with open(sbu_558, 'r') as f:
    data = json.load(f)
print(len(data),data[0])

558128 {'id': '004539375', 'image': '00453/004539375.jpg', 'conversations': [{'from': 'human', 'value': 'Render a clear and concise summary of the photo.\n<image>'}, {'from': 'gpt', 'value': 'select luxury furniture 3 - inch gel memory foam mattress topper'}]}


# TFDS

In [1]:
import matplotlib.pyplot as plt
import tensorflow_datasets as tfds
import tensorflow as tf
dataset = tfds.load('cambrian_dataset/10M:1.0.15', split='train', data_dir='gs://us-central2-storage/tensorflow_datasets/tensorflow_datasets')
len(dataset)

2024-10-27 22:24:53.514964: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-27 22:24:53.538185: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-27 22:24:53.545167: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-27 22:24:53.561397: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-27 22:24:54.455090: W tensorflow/compiler/tf2

40000

In [2]:
sample = next(iter(dataset))
sample.keys()

dict_keys(['conversations', 'image'])

In [3]:
for sample in dataset:
    image = sample['image']
    if not tf.equal(tf.shape(image)[0], 0).numpy():
        print(tf.shape(image))
        print(image[0])
        print(tf.io.decode_image(image[0], channels=3, expand_animations=False))
        break

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.\' ",#\x1c\x1c(7),01444\x1f\'9=82<.342\xff\xdb\x00C\x01\t\t\t\x0c\x0b\x0c\x18\r\r\x182!\x1c!22222222222222222222222222222222222222222222222222\xff\xc0\x00\x11\x08\x02\xd1\x04\x00\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb

In [5]:
sample['conversations']

{'from': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'human', b'gpt'], dtype=object)>,
 'value': <tf.Tensor: shape=(2,), dtype=string, numpy=
 array([b'<image>\nWhich food item might be considered more suitable for someone who avoids spicy food?',
        b'For someone who avoids spicy food, the two hot dogs in the plastic container would be considered a more suitable option. In the image, there is a sub sandwich in another container with jalapeno peppers, which are known to be spicy. Since the hot dogs do not have any visible spicy condiments, they would be a safer option for someone who prefers to stay away from spiciness.'],
       dtype=object)>}